version: "3"

services:
  main_server:
    image: gmihtt/multir_server:latest
    command: stack exec mainServer-exe
    ports:
      - 8082:8082
  
  server1:
    image: gmihtt/multi-layer:latest
    command: stack exec multi-layer-exe
    depends_on:
      - main_server
    ports:
      - 8080:8080
 
  server2:
    image: gmihtt/multi-layer8081:latest
    command: stack exec multi-layer-exe
    depends_on:
      - main_server
    ports:
      - 8081:8081
  
  redis1:
    image: redis:latest
    ports:
      - 6379:6379
    depends_on:
      - server1
  
  redis2:
    image: redis:latest
    ports:
      - 6380:6379
    depends_on:
      - server2

  mongo:
    image: mongo:latest
    depends_on:
      - main_server
      - server1
      - server2
    ports:
      - 27017:27017
