version: "3"

services:
  server2:
    image: multi-layer8081
    command: stack exec server-exe
    ports:
      - 8081:8081
  
  redis2:
    image: redis:latest
    ports:
      - 6380:6379
    depends_on:
      - server2