version: "3"

services:
  server1:
    image: gmihtt/multi-layer
    command: stack exec server-exe
    ports:
      - 8080:8080

  redis1:
    image: redis:latest
    ports:
      - 6379:6379
    depends_on:
      - server1